### ISSUE TITLE
Checksum of Image files to validate the image integrity

### ISSUE THREAD

**Issue by ujwalkomarla** [extremenetworks/Virtual_EXOS#15]
I have a Packer tool script to generate a Vagrant box for EXOS. However, packer needs a checksum(SHA256/MD5) to validate the integrity of the file downloaded. 
If you can provide the checksum along with Image file, that would be great.

Something like this:
Image: https://akamai-ep.extremenetworks.com/Extreme_P/github-en/Virtual_EXOS/vm-30.2.1.8.iso
Checksum: https://akamai-ep.extremenetworks.com/Extreme_P/github-en/Virtual_EXOS/vm-30.2.1.8-sha256sum.txt

**Comment by btclay** [comment]
I just added these in commit c4f28567ac6deaa4ff91cce78cb6a246b83d93a9.

I created a new `checksums` directory for these when I was doing some reorganization, since the checksums for both the ISO files and the .xos files are in the same text file, so it didn't make sense for them to be one directory and not the other.

**Comment by ujwalkomarla** [comment]
Perfect! 
Thanks.
